#    .-============================-.
#  .'   *     .     *     .     *    '.
# /     ____ ___ _   _ _   _ ____      \
# |    |  _ \_ _| \ | | | | |  _ \     |
# |    | |_) | ||  \| | | | | |_) |    |
# |    |  __/| || |\  | |_| |  __/     |
# |    |_|  |___|_| \_|\___/|_|        |
# \                                    /
#  '.    *     .     *     .    *    .'
#    '-============================-'

# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[colors-dark]
alpha=0.888
alpha-mode=all

background=190403
foreground=f1dfbe

cursor=190403 f1dfbe
selection-foreground=190403
selection-background=5f8fd8

regular0=190403
regular1=b45a24
regular2=8da33c
regular3=c5a64f
regular4=5f8fd8
regular5=b86591
regular6=3fa0a6
regular7=f1dfbe

bright0=6f4d3c
bright1=d0793d
bright2=a9bf5a
bright3=d9bd67
bright4=8cb2ee
bright5=d587ae
bright6=68bdc2
bright7=fff1d2

#  ______   __       ______
# /_____/\ /_/\     /_____/\
# \:::_ \ \\:\ \    \:::_ \ \
#  \:\ \ \ \\:\ \    \:\ \ \ \
#   \:\ \ \ \\:\ \____\:\ \ \ \
#    \:\_\ \ \\:\/___/\\:\/.:| |
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
