#    .-============================-.
#  .'   *     .     *     .     *    '.
# /     ____ ___ _   _ _   _ ____      \
# |    |  _ \_ _| \ | | | | |  _ \     |
# |    | |_) | ||  \| | | | | |_) |    |
# |    |  __/| || |\  | |_| |  __/     |
# |    |_|  |___|_| \_|\___/|_|        |
# \                                    /
#  '.    *     .     *     .    *    .'
#    '-============================-'

# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
#


# Background and foreground colors
background = #190403
foreground = #f1dfbe
background-opacity = 0.888

# Standard colors
palette = 0=#190403
palette = 1=#b45a24
palette = 2=#8da33c
palette = 3=#c5a64f
palette = 4=#5f8fd8
palette = 5=#b86591
palette = 6=#3fa0a6
palette = 7=#f1dfbe

# Bright colors
palette = 8=#6f4d3c
palette = 9=#d0793d
palette = 10=#a9bf5a
palette = 11=#d9bd67
palette = 12=#8cb2ee
palette = 13=#d587ae
palette = 14=#68bdc2
palette = 15=#fff1d2

#   ______   __       ______
#  /_____/\ /_/\     /_____/\
#  \:::_ \ \\:\ \    \:::_ \ \
#   \:\ \ \ \\:\ \    \:\ \ \ \
#    \:\ \ \ \\:\ \____\:\ \ \ \
#     \:\_\ \ \\:\/___/\\:\/.:| |
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
#

#  ______   __       ______
# /_____/\ /_/\     /_____/\
# \:::_ \ \\:\ \    \:::_ \ \
#  \:\ \ \ \\:\ \    \:\ \ \ \
#   \:\ \ \ \\:\ \____\:\ \ \ \
#    \:\_\ \ \\:\/___/\\:\/.:| |
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/