#     ____  _           _ _               
#    |  _ \(_)_ __   __| | |_   _ _ __ ___  _ __   ___ 
#    | |_) | | '_ \ / _` | | | | | '_ ` _ \| '_ \ / _ \
#    |  __/| | | | | (_| | | |_| | | | | | | |_) | (_) |
#    |_|   |_|_| |_|\__,_|_|\__,_|_| |_| |_| .__/ \___/ 
#                                           |_|          

$color = rgba(10, 14, 23, 1)
$inner_color = rgba(10, 14, 23, 0.88)
$outer_color = rgba(58, 63, 75, 1)
$font_color = rgba(224, 228, 236, 1)
$placeholder_color = rgba(224, 228, 236, 0.6)
$check_color = rgba(30, 144, 255, 1)
$fail_color = rgba(220, 20, 60, 1)
