#    .-============================-.
#  .'   *     .     *     .     *    '.
# /     ____ ___ _   _ _   _ ____      \
# |    |  _ \_ _| \ | | | | |  _ \     |
# |    | |_) | ||  \| | | | | |_) |    |
# |    |  __/| || |\  | |_| |  __/     |
# |    |_|  |___|_| \_|\___/|_|        |
# \                                    /
#  '.    *     .     *     .    *    .'
#    '-============================-'

# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[colors-dark]
alpha=0.888
alpha-mode=all

background=eee1c3
foreground=190403

cursor=eee1c3 190403
selection-foreground=eee1c3
selection-background=004584

regular0=eee1c3
regular1=6b2e06
regular2=465900
regular3=61620d
regular4=004584
regular5=6d2e52
regular6=00656a
regular7=190403

bright0=b59b72
bright1=944e1e
bright2=657e00
bright3=838707
bright4=2865b6
bright5=964b79
bright6=2b8a90
bright7=391d19

#  ______   __       ______
# /_____/\ /_/\     /_____/\
# \:::_ \ \\:\ \    \:::_ \ \
#  \:\ \ \ \\:\ \    \:\ \ \ \
#   \:\ \ \ \\:\ \____\:\ \ \ \
#    \:\_\ \ \\:\/___/\\:\/.:| |
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
