#    .-============================-.
#  .'   *     .     *     .     *    '.
# /     ____ ___ _   _ _   _ ____      \
# |    |  _ \_ _| \ | | | | |  _ \     |
# |    | |_) | ||  \| | | | | |_) |    |
# |    |  __/| || |\  | |_| |  __/     |
# |    |_|  |___|_| \_|\___/|_|        |
# \                                    /
#  '.    *     .     *     .    *    .'
#    '-============================-'

# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
#


# Background and foreground colors
background = #eee1c3
foreground = #190403
background-opacity = 0.888

# Standard colors
palette = 0=#eee1c3
palette = 1=#6b2e06
palette = 2=#465900
palette = 3=#61620d
palette = 4=#004584
palette = 5=#6d2e52
palette = 6=#00656a
palette = 7=#190403

# Bright colors
palette = 8=#b59b72
palette = 9=#944e1e
palette = 10=#657e00
palette = 11=#838707
palette = 12=#2865b6
palette = 13=#964b79
palette = 14=#2b8a90
palette = 15=#391d19

#   ______   __       ______
#  /_____/\ /_/\     /_____/\
#  \:::_ \ \\:\ \    \:::_ \ \
#   \:\ \ \ \\:\ \    \:\ \ \ \
#    \:\ \ \ \\:\ \____\:\ \ \ \
#     \:\_\ \ \\:\/___/\\:\/.:| |
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
#

#  ______   __       ______
# /_____/\ /_/\     /_____/\
# \:::_ \ \\:\ \    \:::_ \ \
#  \:\ \ \ \\:\ \    \:\ \ \ \
#   \:\ \ \ \\:\ \____\:\ \ \ \
#    \:\_\ \ \\:\/___/\\:\/.:| |
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/